SELECT 
    
    OPERATING_DAY,
    TRIP_IDENTIFIER,
    OPERATOR_ID,
    OPERATOR_ABBR,
    OPERATOR_NAME,
    TRANSPORT_MODE_DE,
    LINE_ID,
    LINE_TEXT,
    CIRCUIT_ID,
    TRANSPORT_MODE_TEXT,
    ADDITIONAL_TRIP_FLAG,
    CANCELLED_FLAG,
    STOP_UIC,
    STOP_NAME,
    ARRIVAL_TIME,
    ARRIVAL_FORECAST,
    NULLIF(ARRIVAL_FORECAST,ARRIVAL_TIME) - ARRIVAL_TIME AS ARRIVAL_DELAY_MIN,
    CASE 
        WHEN (NULLIF(ARRIVAL_FORECAST,ARRIVAL_TIME) - ARRIVAL_TIME) > INTERVAL '3 minutes' THEN 'Late' ELSE 'On Time' END AS ARRIVAL_IS_LATE,
    ARRIVAL_FORECAST_STATUS,
    DEPARTURE_TIME,
    DEPARTURE_FORECAST,
    NULLIF(DEPARTURE_FORECAST,DEPARTURE_TIME) - DEPARTURE_TIME AS DEPARTURE_DELAY_MIN,
    CASE 
        WHEN (NULLIF(DEPARTURE_FORECAST,DEPARTURE_TIME) - DEPARTURE_TIME) > INTERVAL '3 minutes' THEN 'Late' ELSE 'On Time' END AS DEPARTURE_IS_LATE,
    DEPARTURE_FORECAST_STATUS,
    PASS_THROUGH_FLAG,
    SLO_ID
FROM {{ref('ods_daily_transport')}}