SELECT DISTINCT
TRANSPORT_MODE_DE,
 CASE 
        WHEN TRANSPORT_MODE_DE IS NULL THEN -1 
        ELSE hash(TRANSPORT_MODE_DE) END AS TRANPOSRT_MODE_ID,
-- Trad: french
CASE 
        WHEN TRANSPORT_MODE_DE = 'SCHIFF' THEN 'BATEAU'
        WHEN TRANSPORT_MODE_DE = 'BUS'    THEN 'BUS'
        WHEN TRANSPORT_MODE_DE = 'METRO'  THEN 'MÉTRO'
        WHEN TRANSPORT_MODE_DE = 'ZUG'    THEN 'TRAIN'
        WHEN TRANSPORT_MODE_DE = 'ZAHNRADBAHN' THEN 'TRAIN À CRÉMAILLÈRE'
        WHEN TRANSPORT_MODE_DE = 'TRAM'   THEN 'TRAMWAY'
        ELSE 'AUTRE / INCONNU'
    END AS TRANSPORT_MODE_FR,
-- Traduction en Ang
CASE 
        WHEN TRANSPORT_MODE_DE = 'SCHIFF' THEN 'BOAT'
        WHEN TRANSPORT_MODE_DE = 'BUS'    THEN 'BUS'
        WHEN TRANSPORT_MODE_DE = 'METRO'  THEN 'METRO'
        WHEN TRANSPORT_MODE_DE = 'ZUG'    THEN 'TRAIN'
        WHEN TRANSPORT_MODE_DE = 'ZAHNRADBAHN' THEN 'COGWHEEL RAILWAY'
        WHEN TRANSPORT_MODE_DE = 'TRAM'   THEN 'TRAM'
        ELSE 'OTHER / UNKNOWN'
    END AS TRANSPORT_MODE_EN,
    TRANSPORT_MODE_TEXT
FROM {{ref('ods_daily_transport')}}