SELECT
    OPERATING_DAY,
    TRIP_IDENTIFIER,
    OPERATOR_ID,
    OPERATOR_ABBR,
    OPERATOR_NAME,
    TRANSPORT_MODE_DE,
    LINE_ID,
    LINE_TEXT,
    CIRCUIT_ID,
    TRANSPORT_MODE_TEXT,
    ADDITIONAL_TRIP_FLAG,
    CANCELLED_FLAG,
    STOP_UIC,
    STOP_NAME,
    ARRIVAL_TIME,
    ARRIVAL_FORECAST,
    ARRIVAL_DELAY_MIN,
    ARRIVAL_IS_LATE,
    ARRIVAL_FORECAST_STATUS,
    DEPARTURE_TIME,
    DEPARTURE_FORECAST,
    DEPARTURE_DELAY_MIN,
    DEPARTURE_IS_LATE,
    DEPARTURE_FORECAST_STATUS,
    PASS_THROUGH_FLAG,
    SLO_ID
FROM {{ref('ods_daily_transport__delay')}}
WHERE 
    (DEPARTURE_FORECAST_STATUS == 'REAL' OR ARRIVAL_FORECAST_STATUS = 'REAL') 
    AND TRANSPORT_MODE_DE == 'TRAM'